version: '3.4'
services:
    nginx:
        image: nginx:1.14-alpine
        restart: unless-stopped
        depends_on:
            - php-fpm
        volumes:
            - ./webconf/nginx_dev_host.conf:/etc/nginx/nginx.conf:ro
            - ./app/public:/app/public:ro
        expose:
            - 80
        network_mode: host
        
    php-fpm:
        image: php:8.1-fpm-bullseye
        restart: unless-stopped
        user: "%USER%"
        volumes:
            - ./app/:/app
        working_dir: /app
        expose:
            - 9000
        network_mode: host
